# Generated by Django 4.1 on 2022-08-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_alter_supers_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='catch_phrase',
            new_name='catchphrase',
        ),
    ]
