# Generated by Django 4.1 on 2022-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_rename_catch_phrase_supers_catchphrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
