# Generated by Django 4.1 on 2022-08-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0006_rename_super_type_id_supers_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
